# This is a basic workflow to help you get started with Actions

name: BarcodeSimulator CD

# Controls when the workflow will run
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: Nuget/setup-nuget@v1.0.5
        
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: Restore Packages
        run: nuget restore BarcodeSimulator.sln
        
      - name: Build Solution
        run: |
           msbuild.exe BarcodeSimulator.sln /p:platform="Any CPU" /p:configuration="Release"
           
      - name: Create Artifacts
        run: |
          powershell Compress-7Zip "bin\Release" -ArchiveFileName "BarcodeSimulator-AnyCPU.zip" -Format Zip
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated Release by GitHub Action CI
          draft: false
          prerelease: true
          
      - name: Upload Release Asset (AnyCPU)
        id: upload-release-asset-x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .\BarcodeSimulator-AnyCPU.zip
          asset_name: BarcodeSimulator-AnyCPU.zip
          asset_content_type: application/zip
          
           
       
       
